### PR TITLE
Add parser support for adding new events

### LINKED ISSUE #62: Add parser support for adding new events
Child issue of #50 

Will minimally implement up till syntax. Integration with model may or may not be done depending on complexity and my availability.

### PR DESCRIPTION
**Pull request by C5hives**
Resolves #62 and #76

Test cases are currently hardcoded. Will need to be refactored to use utility classes later on.
- Add `CreateEventCommand` and `CreateEventCommandParser`
- Add a new prefix for date, prefix is `on/`
- Command to add an event is `create_event`
- Add case to handle `create_event`
- Added new test cases and updated existing test cases

### CODE REVIEW

**Comment by C5hives** [comment]
@AY2425S1-CS2103-F13-2/developers Due to a recent PR (see #63) made by @hanscau, there is now a conflicting prefix `d/` for `description` and `date`.

Converting this PR into a draft for now until this is sorted out. Will open an issue for this as well.

**Comment by Jasperabez** [comment]
Would be good if our feature specification is updated to reflect the change in the commands, as well as the prefix name change.

Another food for thought is whether we should change all the commands from `<command><space><target>` to `<command>_<target>` as what you have done here

**Comment by hanscau** [comment]
I would prefer if we change it to `<command><space><target>` in the future with `<command>_<target>` as a placeholder for now. But if it's too much work, we can just change our plans

**Review by hanscau — APPROVED** [review]
LGTM! Might want to create issues for the verification TODOs

**Pull request merged**
