### PR TITLE
Update User Guide for delete Command

### LINKED ISSUE #187: Update User Guide for `delete` Command
Child issue of #180

### PR DESCRIPTION
**Pull request by C5hives**
Resolves #187 

Straightforward change.

### CODE REVIEW

**Review by kahsuann — APPROVED** [review]
LGTM

**Review by Jasperabez — APPROVED** [review]
LGTM would it be good to mention that it is possible to delete offscreen indices? For example view v/3 but I can delete v/2

**Comment by C5hives** [comment]
> LGTM would it be good to mention that it is possible to delete offscreen indices? For example view v/3 but I can delete v/2

Worth adding. Will change it

**Review by Jasperabez — APPROVED** [review]
LGTM can consider shifting this disclaimer down at the bottom of user guide later on as most commands function similarly

**Pull request merged**
