### PR TITLE
Add implementation details of the assign and unassign command to DG

### LINKED ISSUE #210: Update DG implementation section with the assign command

### PR DESCRIPTION
**Pull request by kevin-pek**
Resolves #210.

Added implementation details of the `assign` and `unassign` command to the developer guide.

### CODE REVIEW

**Review by Jasperabez — CHANGES_REQUESTED** [review]
Would be better if it was phrased as a standalone application

**Comment by Jasperabez** [comment]
Sequence Diagram:
AssignSequenceDiagram

**Comment by C5hives** [comment]
image

this alt frame should be an optional one because our code looks like this:
image

**Comment by kevin-pek** [comment]
> image
> 
> this alt frame should be an optional one because our code looks like this: image
> 
> everything else is ok!

image

Have modified the sequence diagram to use opt, and made some changes as referenced from a past semester. https://github.com/nus-cs2103-AY2021S1/forum/issues/378

**Review by Jasperabez — APPROVED** [review]
LGTM! very nice 😙🤌

**Pull request merged**
